//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUserRolesService")]
public interface IUserRolesService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRolesService/UserRoles", ReplyAction="http://tempuri.org/IUserRolesService/UserRolesResponse")]
    string UserRoles(string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRolesService/UserRoles", ReplyAction="http://tempuri.org/IUserRolesService/UserRolesResponse")]
    System.Threading.Tasks.Task<string> UserRolesAsync(string userId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserRolesServiceChannel : IUserRolesService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserRolesServiceClient : System.ServiceModel.ClientBase<IUserRolesService>, IUserRolesService
{
    
    public UserRolesServiceClient()
    {
    }
    
    public UserRolesServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserRolesServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserRolesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserRolesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string UserRoles(string userId)
    {
        return base.Channel.UserRoles(userId);
    }
    
    public System.Threading.Tasks.Task<string> UserRolesAsync(string userId)
    {
        return base.Channel.UserRolesAsync(userId);
    }
}
